### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest

### ISSUE THREAD

**Issue by bernardmaltais** [drupalwxt/helm-drupal#21]
I have attempted to deploy the drupalwxt using the helm chart with the following command:

`helm install gocweb --namespace gocweb ./drupal -f ./drupal/values.yaml`

but I run into this error:

```
helm install gocweb --namespace gocweb ./drupal -f ./drupal/values.yaml
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]
```

I am running helm version:
`version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}`

on kubernetes v1.17.3 using k3d:

```
k3d version v1.7.0
k3s version v1.17.3-k3s1
```

**Comment by bernardmaltais** [comment]
I also upgraded to the latest versions of helm (3.1.2) and kubectl (v1.18.1) with the same error.

**Comment by bernardmaltais** [comment]
OK... Look like the dependency charts are too old. I updated them to the latest available versions:

```
dependencies:
  - name: mysql
    version: 1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mysql.enabled
  - name: minio
    version: 5.0.10
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: minio.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
```

Then did a

```
helm dependency build drupal
```

and now things appear to deploy using helm3. Fingers crossed.
