### ISSUE TITLE
Issue deploying the chart

### ISSUE THREAD

**Issue by bmaltais** [drupalwxt/helm-drupal#33]
I am trying to deploy the chart with:

```
kubectl create namespace drupal-wxt
helm install drupal-wxt --namespace gocweb -f values.yaml --wait .

```

but I am getting the following error:

```
helm install drupal-wxt --namespace gocweb -f values.yaml --wait .
Error: template: drupal/charts/minio/templates/deployment.yaml:210:20: executing "drupal/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
```

Look like it is possibly related to minio?

**Comment by bmaltais** [comment]
More info. I found this reference to an issue with the minio template and new version of go: https://community.gitpod.io/t/issues-installing-on-own-k8/1531/5

Not sure what is the relation between them yet...

**Comment by bmaltais** [comment]
More update. I was able to fix the issue by updating the version of minio being deployed to 6.0.5. Look like the old 5.0.x release is not compliant with new version of helm due to golan validation:

```yaml
dependencies:
  - name: mysql
    version: 1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mysql.enabled
  - name: minio
    version: 6.0.5
    repository: https://helm.min.io/
    condition: minio.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled
  - name: varnish
    version: 0.0.2
    repository: https://statcan.github.io/charts
    condition: varnish.enabled
```
