### ISSUE TITLE
varnish will not validate when used in values file

### ISSUE THREAD

**Issue by bernardmaltais** [drupalwxt/helm-drupal#37]
I tried to add the varnish component by configuring the values.yaml file as shown in the example values files. Unfortunatly it result in a strange error as see below:

```bash
vscode ➜ /tf/caf (master ✗) $ helm upgrade drupal-wxt --namespace drupal-wxt --reuse-values -f values-azure-upgrade.yaml drupalwxt/drupal
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec): unknown field "annotations" in io.k8s.api.core.v1.PodSpec
```

The values for varnish I tried to use are the following. I even tried adding an annotations section but no luck:

```yaml
## Configuration values for the Varnish dependency sub-chart
## ref: https://github.com/StatCan/charts/blob/master/stable/varnish/README.md
varnish:
  enabled: true
  varnishd:
    image: varnish
    tag: 6.4.0
    imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  #  requests:
  #    memory: "512Mi"
  #    cpu: "100m"
  #  limits:
  #    memory: "1Gi"
  #    cpu: "500m"
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
```

Any ideas?
