### ISSUE TITLE
Varnish, $settings['trusted_host_patterns'] and HTTP 400 errors

### ISSUE THREAD

**Issue by patheard** [drupalwxt/helm-drupal#54]
A gotcha I just discovered is that if you're using Varnish and have Drupal `trusted_host_patterns` set, you'll need to add a host pattern for your Drupal pod.  

In our case, the Helm release is called `drupal-wxt-dev`, so this does the trick:

```yaml
varnish:
  enabled: true

extraSettings: |-
  $settings['trusted_host_patterns'] = ['^somedomain\.com$', '^drupal-wxt-dev.*$'];
```

Happy to submit a PR documenting this if you let me know where you'd like it.
