### ISSUE TITLE
Ability to keep last install/upgrade job pods

### ISSUE THREAD

**Issue by bernardmaltais** [drupalwxt/helm-drupal#89]
I have had many occurrence where Drupal upgrade goes failing due to some issue with drush cim or drush updb. The current job will be deleted after 5 failed execution. Would it be possible to retain the last job pod to facilitate log reviews? I think the parameter for that might be:

```yaml
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
```

to

```yaml
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
```

What do you think? Possibility?
